apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
localAPIEndpoint:
  advertiseAddress: "192.168.2.50"
  bindPort: 6443        
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
clusterName: microbot-cluster
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  CertSANs:
  - "machine01"
  - "microbot.moonstreet.local"  
etcd:
  local:
    serverCertSANs:
      - "machine01"
      - "192.168.2.50"
    peerCertSANs:
      - "192.168.2.50"
      - "machine01"
